### ISSUE TITLE
Create checkbox instead of radio buttons for selected number of questions.

### ISSUE THREAD

**Issue by mkiourlappou** [carandraug/mRNA-localisation-screening#6]
It would be very useful to have checkboxes instead of radio buttons for some of the questions. This is to select more than one answers to the questions. 

Perhaps if it's possible we could have a parameter in the questions file which specifies if there is only a single answer to a question or if there are more than one. Is this possible?

**Comment by carandraug** [comment]
We can add more options and parameters, the config files just get a bit more complicated but maybe that's not a big deal.

However, how do you expect output to look like? At the moment, for each question you get a string back which is the given answer. We could change the code to have a string or a list which is messy but if that  works for you...

**Comment by mkiourlappou** [comment]
At the moment we parse the pickle file using a python script, which creates a dataframe with each cell containing each string output (one cell per answer). So I think that since the multiple selection would be an answer to one question, perhaps a string containing a list of answers would be ok. 

I hope that makes sense and it's not such a bad idea! Thank you :)

**Comment by carandraug** [comment]
> [...] perhaps a string containing a list of answers would be ok.

You either get a list, which can be of strings, or you get a string which is a list of characters, not of answers. If you want to keep have a single string for this multi-answer question, then you will need a separator character that can't appear on the single answer questions (and don't forget about the questions where a person can write anything), or that you pair the answers with more metadata of the questions.

**Comment by mkiourlappou** [comment]
I think a separator character would work. I can use the separator character to separate the answers when I parse the file so should be ok! :)

**Comment by carandraug** [comment]
If you want a separator character, then I think the tab might be the best since that's one unlikely to be used on the answer box. Will it be ok for analysis if you can't distinguish between single choice question and a multi choice question where only one answer was selected?

**Comment by mkiourlappou** [comment]
That's a clever idea, I think yes it would work! Since the tab is not separating the answers too different questions I believe for analysis it would be ok to have tab to separate the answers to the same question. If only one answer is selected I believe would be ok since it would be separated by the next answer by the same way as normally. (I hope this makes sense) Thank you!

**Comment by carandraug** [comment]
I have done as you asked and pushed 28d32d6e3705 .

Note that as I mentioned before that required changing how the config file looks like. I don't think it's much more complex, just different. I have adjusted the documentation accordingly.
